---
title: "Plots"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```


```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
data("instacart")
```


### Scatterplot

```{r}
instacart2 = instacart %>% 
  filter(product_id < 20)
```

Scatterplot of the hour an item was ordered by the number of items ordered. 

```{r}
instacart2 %>% 
  plot_ly (x = ~add_to_cart_order, y = ~order_hour_of_day, type = "scatter", mode = "markers", alpha = 0.5, color = ~product_id)
```

### Boxplot 

```{r}
instacart1 = instacart %>% 
  filter(product_id < 50)
```

Boxplot of the days since the prior order by each department.

```{r}
instacart1 %>% 
  mutate(department = fct_reorder(department, days_since_prior_order)) %>% 
  plot_ly(y = ~days_since_prior_order, color = ~department, type = "box", colors = "viridis")
```

### Histogram 

Histogram of the number of items ordered in each department.

```{r}
instacart %>% 
  count(department) %>% 
  mutate(
    department = factor(department),
    department = fct_reorder(department, n)) %>% 
  plot_ly (x = ~department, color = ~department, y = ~n, type = "bar", colors = "viridis")
```

